<?php

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function ttsaudio_option_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function ttsaudio_option_add_meta_box() {
	add_meta_box(
		'ttsaudio_option-ttsaudio-option',
		__( 'TTSAudio Option', 'ttsaudio_option' ),
		'ttsaudio_option_html',
		'post',
		'normal',
		'default'
	);
	add_meta_box(
		'ttsaudio_option-ttsaudio-option',
		__( 'TTSAudio Option', 'ttsaudio_option' ),
		'ttsaudio_option_html',
		'page',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'ttsaudio_option_add_meta_box' );

function ttsaudio_option_html( $post) {

	$options = get_option( TTSAUDIO_OPTION );
  $tts = new TTSAudio;

	wp_nonce_field( '_ttsaudio_option_nonce', 'ttsaudio_option_nonce' ); ?>
	<table id="ttsaudio_form" class="form-table"><tbody>
	<tr>
		<th><label for="ttsaudio_option_tts_audio"><?php _e( 'TTS Audio', 'ttsaudio_option' ); ?></label></th>
		<td>
			<select name="ttsaudio_option_tts_audio" id="ttsaudio_option_tts_audio">
				<option <?php echo (ttsaudio_option_get_meta( 'ttsaudio_option_tts_audio' ) === 'enable' ) ? 'selected' : '' ?>>Enable</option>
				<option <?php echo (ttsaudio_option_get_meta( 'ttsaudio_option_tts_audio' ) === 'disable' ) ? 'selected' : '' ?>>Disable</option>
			</select>
		</td>
	</tr>
	<tr>
		<th><label for="ttsaudio_option_voice"><?php _e( 'Voice', 'ttsaudio_option' ); ?></label></th>
		<td><select name="ttsaudio_option_voice" id="ttsaudio_option_voice">
			<?php foreach ($tts->voices as $key => $value) {?>
			<option value="<?php esc_attr_e($key);?>"><?php esc_html_e($value);?></option>
			<?php } ?>
		</select>
		<p>You can set Default Voice in <a href="<?php echo menu_page_url('ttsaudio', 0);?>" target="_blank">TTS Audio Options</a></p>
	</td>
	</tr>
	<tr>
		<th><label for="ttsaudio_option_text_to_speech_"><?php _e( 'Text (to speech)', 'ttsaudio_option' ); ?></label></th>
		<td>
			<textarea class="large-text" rows="10" name="ttsaudio_option_text_to_speech_" id="ttsaudio_option_text_to_speech_" ><?php echo ttsaudio_option_get_meta( 'ttsaudio_option_text_to_speech_' ); ?></textarea>
			<p>Separate paragraph with double blank lines.</p>
		</td>

	</tr>
	</tbody></table>
	<?php
}

function ttsaudio_option_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['ttsaudio_option_nonce'] ) || ! wp_verify_nonce( $_POST['ttsaudio_option_nonce'], '_ttsaudio_option_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['ttsaudio_option_tts_audio'] ) )
		update_post_meta( $post_id, 'ttsaudio_option_tts_audio', esc_attr( $_POST['ttsaudio_option_tts_audio'] ) );
	if ( isset( $_POST['ttsaudio_option_voice'] ) )
		update_post_meta( $post_id, 'ttsaudio_option_voice', esc_attr( $_POST['ttsaudio_option_voice'] ) );
	if ( isset( $_POST['ttsaudio_option_text_to_speech_'] ) )
		update_post_meta( $post_id, 'ttsaudio_option_text_to_speech_', esc_attr( $_POST['ttsaudio_option_text_to_speech_'] ) );
}
add_action( 'save_post', 'ttsaudio_option_save' );

/*
	Usage: ttsaudio_option_get_meta( 'ttsaudio_option_tts_audio' )
	Usage: ttsaudio_option_get_meta( 'ttsaudio_option_voice' )
	Usage: ttsaudio_option_get_meta( 'ttsaudio_option_text_to_speech_' )
*/
