<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class TTSAudio_Options {
	private $ttsaudio_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'ttsaudio_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'ttsaudio_page_init' ) );
	}

	public function ttsaudio_add_plugin_page() {
		add_menu_page(
			'TTSAudio', // page_title
			'TTSAudio', // menu_title
			'manage_options', // capability
			'ttsaudio', // menu_slug
			array( $this, 'ttsaudio_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
		);
	}

	public function ttsaudio_create_admin_page() {
		$this->ttsaudio_options = get_option( 'ttsaudio_option_name' ); ?>

		<div class="wrap">
			<h2>TTSAudio</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'ttsaudio_option_group' );
					do_settings_sections( 'ttsaudio-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function ttsaudio_page_init() {
		register_setting(
			'ttsaudio_option_group', // option_group
			'ttsaudio_option_name', // option_name
			array( $this, 'ttsaudio_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'ttsaudio_setting_section', // id
			'Settings', // title
			array( $this, 'ttsaudio_section_info' ), // callback
			'ttsaudio-admin' // page
		);

		add_settings_field(
			'skin_0', // id
			'Skin', // title
			array( $this, 'skin_0_callback' ), // callback
			'ttsaudio-admin', // page
			'ttsaudio_setting_section' // section
		);

		add_settings_field(
			'default_voice_1', // id
			'Default Voice', // title
			array( $this, 'default_voice_1_callback' ), // callback
			'ttsaudio-admin', // page
			'ttsaudio_setting_section' // section
		);

		add_settings_field(
			'fpt_api_key_2', // id
			'FPT API Key', // title
			array( $this, 'fpt_api_key_2_callback' ), // callback
			'ttsaudio-admin', // page
			'ttsaudio_setting_section' // section
		);
	}

	public function ttsaudio_sanitize($input) {

		$sanitary_values = array();
		if ( isset( $input['skin_0'] ) ) {
			$sanitary_values['skin_0'] = $input['skin_0'];
		}

		if ( isset( $input['default_voice_1'] ) ) {
			$sanitary_values['default_voice_1'] = $input['default_voice_1'];
		}

		if ( isset( $input['fpt_api_key_2'] ) ) {
			$sanitary_values['fpt_api_key_2'] = sanitize_text_field( $input['fpt_api_key_2'] );
		}

		return apply_filters('ttsaudio_sanitize', $input, $sanitary_values);

		//return $sanitary_values;
	}

	public function ttsaudio_section_info() {
		print_r($this->ttsaudio_options);
	}

	public function skin_0_callback() {
		?> <select name="ttsaudio_option_name[skin_0]" id="skin_0">
			<?php $selected = (isset( $this->ttsaudio_options['skin_0'] ) && $this->ttsaudio_options['skin_0'] === 'skin_1') ? 'selected' : '' ; ?>
			<option value="skin_1" <?php echo $selected; ?>>Skin 1</option>
			<?php $selected = (isset( $this->ttsaudio_options['skin_0'] ) && $this->ttsaudio_options['skin_0'] === 'skin_2') ? 'selected' : '' ; ?>
			<option value="skin_2" <?php echo $selected; ?>>Skin 2</option>
		</select> <?php
	}

	public function default_voice_1_callback() {
		?> <select name="ttsaudio_option_name[default_voice_1]" id="default_voice_1">
			<?php $selected = (isset( $this->ttsaudio_options['default_voice_1'] ) && $this->ttsaudio_options['default_voice_1'] === 'voice_1') ? 'selected' : '' ; ?>
			<option value="voice_1" <?php echo $selected; ?>>Voice 1</option>
			<?php $selected = (isset( $this->ttsaudio_options['default_voice_1'] ) && $this->ttsaudio_options['default_voice_1'] === 'voice_21') ? 'selected' : '' ; ?>
			<option value="voice_21" <?php echo $selected; ?>>Voice 2</option>
		</select> <?php
	}

	public function fpt_api_key_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="ttsaudio_option_name[fpt_api_key_2]" id="fpt_api_key_2" value="%s">',
			isset( $this->ttsaudio_options['fpt_api_key_2'] ) ? esc_attr( $this->ttsaudio_options['fpt_api_key_2']) : ''
		);
	}

}
if ( is_admin() )
	$ttsaudio = new TTSAudio_Options();

/*
 * Retrieve this value with:
 * $ttsaudio_options = get_option( 'ttsaudio_option_name' ); // Array of All Options
 * $skin_0 = $ttsaudio_options['skin_0']; // Skin
 * $default_voice_1 = $ttsaudio_options['default_voice_1']; // Default Voice
 * $fpt_api_key_2 = $ttsaudio_options['fpt_api_key_2']; // FPT API Key
 */
